<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Víctor H Cervantes" />

<meta name="date" content="2014-12-06" />

<title>Reproducible Research: Peer Assessment 1</title>

<script src="PA1_template_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.1/css/cerulean.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.1/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="PA1_template_files/highlight/default.css"
      type="text/css" />
<script src="PA1_template_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Reproducible Research: Peer Assessment 1</h1>
<h4 class="author"><em>Víctor H Cervantes</em></h4>
<h4 class="date"><em>12/06/2014</em></h4>
</div>


<p>This document presents the analyses on data from an anonymous individual on his personal <a href="https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip">Activity monitoring data</a>, retrieved on December 5, 2014 from the associated url. Especifically, the activity recorded corresponds to the number of steps taken by the person on 5 minute intervals.</p>
<p>The goal of these analyses is to identify whether there are certain patterns in this person’s activity during the day. Additionally, this document illustrates the use of [R Markdown] (<a href="http://rmarkdown.rstudio.com/">http://rmarkdown.rstudio.com/</a>) and [knitr] (<a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>) as tools for literate programming.</p>
<p>The following code sets some global options for the document and the analyses.</p>
<pre class="r"><code># # Global variables
inPath  &lt;- &#39;./input&#39;
figPath &lt;- &#39;./PA1_template_files/figure-html/&#39;

# # Load packages
library(&quot;ggplot2&quot;)
library(&quot;xtable&quot;)</code></pre>
<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>1. Loading and preprocessing the data</h2>
<p>Firstly, the data will be loaded and preprocessed for the anlyses. The following code loads and examines the data.</p>
<pre class="r"><code>activityFile &lt;- &#39;activity.csv&#39;
dataActivity &lt;- read.csv(file.path(inPath, activityFile))

str(dataActivity)</code></pre>
<pre><code>## &#39;data.frame&#39;:    17568 obs. of  3 variables:
##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ date    : Factor w/ 61 levels &quot;2012-10-01&quot;,&quot;2012-10-02&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...</code></pre>
<p>As presented above, there are three variables in the dataset: <em>steps</em>, <em>date</em>, and <em>interval</em>. Given that the date has the format “yyyy-mm-dd”, the next code process it into a date variable according to that format.</p>
<pre class="r"><code>dataActivity[, &#39;date&#39;] &lt;- as.Date(dataActivity[, &#39;date&#39;], &#39;%Y-%m-%d&#39;)</code></pre>
<p>The following code shows some detail on the values of each variable.</p>
<pre class="r"><code>print(xtable(summary(dataActivity[, c(&#39;steps&#39;, &#39;interval&#39;, &#39;date&#39;)])),
      type = &#39;html&#39;, include.rownames = FALSE)</code></pre>
<!-- html table generated in R 3.1.2 by xtable 1.7-3 package -->
<!-- Sun Dec  7 00:31:47 2014 -->
<TABLE border=1>
<TR> <TH>     
steps
</TH> <TH>    
interval
</TH> <TH>      
date
</TH>  </TR>
  <TR> <TD> 
Min. : 0.0
</TD> <TD> 
Min. : 0
</TD> <TD> 
Min. :2012-10-01
</TD> </TR>
  <TR> <TD> 
1st Qu.: 0.0
</TD> <TD> 
1st Qu.: 589
</TD> <TD> 
1st Qu.:2012-10-16
</TD> </TR>
  <TR> <TD> 
Median : 0.0
</TD> <TD> 
Median :1178
</TD> <TD> 
Median :2012-10-31
</TD> </TR>
  <TR> <TD> 
Mean : 37.4
</TD> <TD> 
Mean :1178
</TD> <TD> 
Mean :2012-10-31
</TD> </TR>
  <TR> <TD> 
3rd Qu.: 12.0
</TD> <TD> 
3rd Qu.:1766
</TD> <TD> 
3rd Qu.:2012-11-15
</TD> </TR>
  <TR> <TD> 
Max. :806.0
</TD> <TD> 
Max. :2355
</TD> <TD> 
Max. :2012-11-30
</TD> </TR>
  <TR> <TD> 
NA’s :2304
</TD> <TD>  </TD> <TD>  </TD> </TR>
   </TABLE>

<p>It should be noted that there are several missing data for the steps variable, and that the data covers a period of two months:</p>
<ol style="list-style-type: decimal">
<li><p>October 2012</p></li>
<li><p>November 2012</p></li>
</ol>
<pre class="r"><code>dataActivity[, &#39;day&#39;]     &lt;- weekdays.Date(dataActivity[, &#39;date&#39;])
dataActivity[, &#39;weekend&#39;] &lt;- dataActivity[, &#39;day&#39;] %in% c(&#39;Saturday&#39;, &#39;Sunday&#39;)</code></pre>
</div>
<div id="what-is-mean-total-number-of-steps-taken-per-day" class="section level2">
<h2>2. What is mean total number of steps taken per day?</h2>
<p>Firstly, we wish to know broadly the amount of steps taken by this person each day. The following code obtains the histogram and basic descriptives of the daily average steps.</p>
<pre class="r"><code>dailyActivity &lt;- aggregate(dataActivity[, &#39;steps&#39;],
                           by = list(date = dataActivity[, &#39;date&#39;]),
                           mean, na.rm = TRUE)

names(dailyActivity)[names(dailyActivity) == &#39;x&#39;] &lt;- &#39;steps&#39;

histogramSteps &lt;- ggplot(dailyActivity[complete.cases(dailyActivity), ],
                         aes(x = steps, y = ..density..))
histogramSteps &lt;- histogramSteps + geom_histogram(binwidth = 4.6)
histogramSteps &lt;- histogramSteps + geom_density()
histogramSteps</code></pre>
<p><img src="PA1_template_files/figure-html/average.png" title="plot of chunk average" alt="plot of chunk average" width="768" /></p>
<pre class="r"><code>summSteps &lt;- summary(dailyActivity[, &#39;steps&#39;], na.rm = TRUE)
summSteps</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.14   30.70   37.40   37.40   46.20   73.60       8</code></pre>
<p>The distribution of steps per day clearly skews towards the left, as seen in the histogram; however, the numeric summary shows that the mean and median are equal (37.4) and both the quartiles, and the minimum and maximum, are about equally separate from them. The average number of steps on a five-minute interval ranges from almost none to about 75, per day.</p>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>3. What is the average daily activity pattern?</h2>
<p>To see if there is a pattern on the activity for this person during the day, a plot on the average number of steps taken on each of the 288 five-minute intervals is presented –as a function of the number of minutes, rather than the interval label. Vertical lines in the plot depict 2-hour intervals.</p>
<pre class="r"><code>intervalActivity &lt;- aggregate(dataActivity[, &#39;steps&#39;],
                              by = list(interval = dataActivity[, &#39;interval&#39;]),
                           mean, na.rm = TRUE)

names(intervalActivity)[names(intervalActivity) == &#39;x&#39;] &lt;- &#39;steps&#39;
intervalActivity[, &#39;minutes&#39;] &lt;- seq(0, 5*287, length = 288)

timeSeriesPlot &lt;- ggplot(intervalActivity[complete.cases(intervalActivity), ],
                         aes(x = minutes, y = steps))
timeSeriesPlot &lt;- timeSeriesPlot + geom_vline(xintercept = seq(from = 0,
                                                               length = 12,
                                                               by = 120),
                                              colour = &#39;darkgrey&#39;)
timeSeriesPlot &lt;- timeSeriesPlot + geom_line()

timeSeriesPlot</code></pre>
<p><img src="PA1_template_files/figure-html/timeSeriesplot.png" title="plot of chunk timeSeriesplot" alt="plot of chunk timeSeriesplot" width="768" /></p>
<pre class="r"><code>maxSteps &lt;- which(intervalActivity[, &#39;steps&#39;] == max(intervalActivity[, &#39;steps&#39;]))

timeMax  &lt;- intervalActivity[maxSteps, &#39;interval&#39;]
hourMax  &lt;- floor(timeMax/100)
minMax   &lt;- 100 * ((timeMax/100) - hourMax)
stepsMax &lt;- intervalActivity[maxSteps, &#39;steps&#39;]</code></pre>
<p>It may be noted that there is a high peak of activity after 8am. Particularly, the highest number of steps occurs, on average, for the five-minute interval beginning at 8:35am, with 206.1698 steps. Several smaller peaks occur at noon, 4pm, and around 7pm.</p>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>4. Imputing missing values</h2>
<p>As noted above, there are several hundreds of missing observations in the steps variable in the data set. Especifically, there are 2304 missing observations.</p>
<p>The following model will serve to impute the missing values. For these analyses, the imputed value will simply be the mean number of steps taken by this person during the same weekday and same interval, for those days with measured number of steps.</p>
<pre class="r"><code>stepsMod &lt;- lm(dataActivity[, &#39;steps&#39;] ~ dataActivity[, &#39;day&#39;]
               + as.factor(dataActivity[, &#39;interval&#39;]))

predictedData &lt;- predict(object = stepsMod, newdata = dataActivity)

isMissing &lt;- is.na(dataActivity[, &#39;steps&#39;])
imputedActivity &lt;- dataActivity
imputedActivity[isMissing, &#39;steps&#39;] &lt;- predictedData[isMissing]

imputedActivity[, &#39;weekend&#39;] &lt;- factor(imputedActivity[, &#39;weekend&#39;],
                                       labels = c(&#39;Weekday&#39;, &#39;Weekend&#39;))</code></pre>
<p>To assess the effect of the imputed values on the statistics, firstly, note that all missing observations were imputed. Next, the histogram and descriptive statistics shown earlier are presented for the imputed dataset.</p>
<pre class="r"><code>prod(complete.cases(imputedActivity))</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>dailyImputedActivity &lt;- aggregate(imputedActivity[, &#39;steps&#39;],
                           by = list(date = imputedActivity[, &#39;date&#39;]),
                           mean, na.rm = TRUE)

names(dailyImputedActivity)[names(dailyImputedActivity) == &#39;x&#39;] &lt;- &#39;steps&#39;

histogramImputedSteps &lt;- ggplot(dailyImputedActivity,
                         aes(x = steps, y = ..density..))
histogramImputedSteps &lt;- histogramImputedSteps + geom_histogram(binwidth = 4.6)
histogramImputedSteps &lt;- histogramImputedSteps + geom_density()
histogramImputedSteps</code></pre>
<p><img src="PA1_template_files/figure-html/averageImputed.png" title="plot of chunk averageImputed" alt="plot of chunk averageImputed" width="768" /></p>
<pre class="r"><code>summImputedSteps &lt;- summary(dailyImputedActivity[, &#39;steps&#39;], na.rm = TRUE)
summImputedSteps</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.14   31.00   38.20   37.60   44.50   73.60</code></pre>
<p>It may be seen that the histogram appear now more symmetric than the original one. Also, the mean and median are no longer equal, and as should be expected from the method emplyed, both quartiles are now closer to the mean of the distribution. The numerical differences do not seem to be too high; however no significance test is performed to corroborate if they are statistically significant.</p>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>5. Are there differences in activity patterns between weekdays and weekends?</h2>
<p>Finally, we wish to evaluate if there are different patterns during the weekends with respect to the weekdays in the activity. The following code shows plots the average number of steps taken on each of the 288 five-minute intervals according to the period of the week they were taken.</p>
<pre class="r"><code>weekendActivity &lt;- aggregate(imputedActivity[, &#39;steps&#39;],
                              by = list(interval = imputedActivity[, &#39;interval&#39;],
                                        period = imputedActivity[, &#39;weekend&#39;]),
                           mean, na.rm = TRUE)

names(weekendActivity)[names(weekendActivity) == &#39;x&#39;] &lt;- &#39;steps&#39;
weekendActivity[, &#39;minutes&#39;] &lt;- seq(0, 5*287, length = 288)

impTimeSeriesPlot &lt;- ggplot(weekendActivity,
                         aes(x = minutes, y = steps, group = period))
impTimeSeriesPlot &lt;- impTimeSeriesPlot + geom_vline(xintercept = seq(from = 0,
                                                               length = 12,
                                                               by = 120),
                                              colour = &#39;darkgrey&#39;)
impTimeSeriesPlot &lt;- impTimeSeriesPlot + geom_line() + facet_grid(period ~ .)

impTimeSeriesPlot</code></pre>
<p><img src="PA1_template_files/figure-html/weekendTimeSeriesplot.png" title="plot of chunk weekendTimeSeriesplot" alt="plot of chunk weekendTimeSeriesplot" width="768" /></p>
<p>It may be noted that the activity is more regular during the weekends for the interval between 8am and 6pm than for the same interval during weekdays, although the peak activity occurs during the weekdays.</p>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
